g4-common: avoid enforce_uses_libraries.status errors
FAILED: out/target/common/obj/APPS/MiuiCamera_intermediates/enforce_uses_libraries.status
/bin/bash -c "(rm -f out/target/common/obj/APPS/MiuiCamera_intermediates/enforce_uses_libraries.status ) && (build/soong/scripts/manifest_check.py 	  --enfor
ce-uses-libraries 	  --enforce-uses-libraries-status out/target/common/obj/APPS/MiuiCamera_intermediates/enforce_uses_libraries.status 	  --aapt out/host
/linux-x86/bin/aapt 	   	   	   	   	  vendor/xiaomi/MiuiCamera/system/priv-app/MiuiCamera/MiuiCamera.apk )"
error: mismatch in the <uses-library> tags between the build system and the manifest:
	- required libraries in build system: []
	                 vs. in the manifest: [miui-stat.jar, cloud-common.jar, volley.jar]
	- optional libraries in build system: []
	                 vs. in the manifest: [zxing.jar]
	- tags in the manifest (vendor/xiaomi/MiuiCamera/system/priv-app/MiuiCamera/MiuiCamera.apk):
		uses-library-not-required:'zxing.jar'		uses-library:'miui-stat.jar'		uses-library:'cloud-common.jar'		uses-library:'vol
ley.jar'
note: the following options are available:
	- to temporarily disable the check on command line, rebuild with RELAX_USES_LIBRARY_CHECK=true (this will set compiler filter "verify" and disable AOT-co
mpilation in dexpreopt)
	- to temporarily disable the check for the whole product, set PRODUCT_BROKEN_VERIFY_USES_LIBRARIES := true in the product makefiles
	- to fix the check, make build system properties coherent with the manifest
	- see build/make/Changes.md for details

06: 13:14 ninja failed with: exit status 1

Signed-off-by: OdSazib <odsazib@gmail.com>
Change-Id: Ic5a177c3374bdd1416e64670ed13be6fac8eb314