g4-common: Move RIL prop ro.telephony.default_network=12 to PRODUCT_PROPERTY_OVERRIDES
 * Because

   error: found duplicate sysprop assignments:
   ro.telephony.default_network=12
   ro.telephony.default_network=9
   ninja failed with: exit status 1

Signed-off-by: XtremeOrnob <xtreme.ornob@gmail.com>